import type { Metadata } from "next";
import { Vazirmatn, Roboto_Mono } from "next/font/google";
import "./globals.css";

const roboto = Vazirmatn({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${robotoMono.variable} antialiased`}
      >
        <div className="flex justify-center">
          <div className="max-w-6xl">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
